import Head from "next/head";
import React from "react";

import FuncionaSection1 from "../components/funciona/FuncionaSection1";
import FuncionaSection2 from "../components/funciona/funcionaSection2/FuncionaSection2";
import FuncionaUniPackages from "../components/funciona/FuncionaSection3/FuncionaUniPackages";
import FuncionaSection4 from "../components/funciona/funcionaSection4/FuncionaSection4";
import FuncionaOndeEstamos from "../components/funciona/funcionaSection5/FuncionaSection5";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <FuncionaSection1 />
        <FuncionaSection2 />
        <FuncionaUniPackages />
        <FuncionaSection4 />
        <FuncionaOndeEstamos />
      </div>
    </div>
  );
}
