import Head from "next/head";
import React from "react";


import FuncionaSection1 from "../components/funciona/FuncionaSection1";
import FuncionaSection2 from "../components/funciona/funcionaSection2/FuncionaSection2";
import FuncionaSection3 from "../components/funciona/funcionaSection3/FuncionaSection3";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        
        <FuncionaSection1 />
        <FuncionaSection2 />
        <FuncionaSection3 />
      </div>
    </div>
  );
}
