import Head from "next/head";
import React from "react";

import UnideskHero from "../components/unidesk/unideskHero/UnideskHero"


export default function Unidesk() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <UnideskHero />
      </div>
    </div>
  );
}
