INSERT INTO blogs(id,slug,title,description,image,category) VALUES ('e9da721c-eae0-416c-879c-e3d58a9d168e','mWqhEqZjPq','5 BENEFÍCIOS EM RESERVAR O TEU QUARTO COM ANTECEDÊNCIA','5 BENEFÍCIOS EM RESERVAR O TEU QUARTO COM ANTECEDÊNCIA
Ir estudar para a universidade é quase sempre sinónimo de ir viver para outra cidade. É por isso que a vida académica marca também o início de um ciclo pessoal, já que representa a primeira grande forma de independência e de emancipação dos jovens, que saem da casa dos pais, vão morar muitas vezes com alguém novo e mudam-se para uma localidade diferente. 

Esse é um momento muito importante na vida das famílias, mas pode também ser relativamente difícil. Afinal de contas, não é fácil encontrar um quarto ou uma casa para arrendar noutra cidade, estando à distância, ainda para mais numa altura em que o mercado imobiliário está altamente inflacionado à conta da interferência do mercado turístico. É por isso que é recomendável procurar tratar disso o mais atempadamente possível.
Existem vários benefícios em encontrar e reservar um quarto com antecedência, ainda para mais num período como este. Eis 5 razões pelas quais o deve fazer o mais cedo possível, na preparação da sua viagem e da sua mudança, de forma a minimizar possíveis dores de cabeça e imprevistos que possam surgir.

MAIOR SEGURANÇA
Reservar um quarto com antecedência confere maior segurança à sua mudança e viagem, já que lhe permite ter uma rede de segurança para fazer face a determinados imprevistos. Por exemplo, permite-lhe uma comunicação mais regular e duradoura com o senhorio, caso necessite de adiar ou antecipar a sua viagem por qualquer motivo, por exemplo. Além disso, ao despachar logo esse problema, acaba por se ver livre de uma dor de cabeça que pode se tornar numa preocupante panela de pressão. 

2. GARANTE MELHORES PREÇOS
Existe uma ideia errada de que esperar por um período mais perto da data lhe proporciona melhores preços. Talvez dantes fosse assim, com senhorios que não conseguiam encontrar arrendatários e baixavam os preços dos seus imóveis sob o prejuízo de ficarem com eles desocupados. Mas actualmente, com o aumento brutal da procura, isso é um cenário que raramente acontece e que é extremamente improvável. Assim, o recomendado para garantir os melhores preços é mesmo optar por fazer a sua reserva o mais atempadamente possível. E já para não falar que isso o auxilia na organização financeira da mudança.

3. MAIS TEMPO PARA PLANEAR A MUDANÇA
Mudar de cidade não é uma tarefa simples. Ainda por mais por um período de tempo prolongado. Por isso, todo o tempo disponível nunca será pouco. Assim, ao reservar o seu quarto o mais atempadamente possível, isso garantir-lhe-á mais tempo livre para planear a viagem, a mudança e todos os aspectos logísticos relacionados. E poderá faze-lo com maior disponibilidade mental, diminuindo os níveis de stress e ansiedade.

4. ENCONTRA AS MELHORES OPORTUNIDADES
É natural que o preço da renda de um quarto é um factor determinante em qualquer escolha, quer o queiramos quer não. Afinal de contas, é o dinheiro que faz girar o mundo. No entanto, há que reconhecer que há outras características igualmente importantes. E quanto mais cedo procurar por um quarto para reservar e arrendar, maior é a probabilidade de encontrar uma melhor opção. Já diz a sabedoria popular que Deus ajuda quem cedo madruga e a sabedoria popular não se costuma enganar. Ao começar a procurar mais cedo, tem mais chances de encontrar melhores ofertas e oportunidades de negócio, até porque a procura não será ainda tão intensa quanto o será mais tarde.

5. PREPARE A SUA CHEGADA
Ao arranjar um quarto com antecedência não só está a garantir melhores condições para planear a sua mudança, como está a preparar melhor a sua chegada. Ou seja, pode pesquisar a sua zona de residência, perceber quais são os serviços que existem nas imediações, estudar a rede de transportes públicos e pesquisar os restaurantes e os cafés melhor avaliados na internet. Tudo isso para que, ao chegar à nova cidade, não seja apanhado desprevenido ou ser surpreendido com alguma surpresa menos agradável.
','/images/blog/mWqhEqZjPq.jpeg','TENANT');
INSERT INTO blogs(id,slug,title,description,image,category) VALUES ('53e0f12a-c8f9-4940-86b2-df526f11de0c','VxMioAYAZM','SOBREVIVER À UNIVERSIDADE - UM GUIA COMPLETO','SOBREVIVER À UNIVERSIDADE - UM GUIA COMPLETO
Dizem que a universidade são os melhores tempos da nossa vida. E, na maioria das vezes, estão correctos. Mas obviamente que é também um período de grandes desafios. E não estamos a referir-nos às ressacas, que podem ser também muito duras.

A verdade é que a vida universitária exige uma grande coordenação entre saúde mental, gestão de tempo e aplicação financeira correcta, de forma a garantir que entrega os trabalhos todos a tempo, tem aproveitamento positivo e consegue manter uma vida social satisfatória e agradável. O que, sejamos sinceros, não é fácil para quem está pela primeira vez a experimentar a independência e a autonomia pessoal. Por isso, para o auxiliar nesse processo, criámos este guia completo de como sobreviver à universidade em 5 simples dias.

APRENDA A GERIR O SEU ORÇAMENTO
A parte financeira é uma das mais difíceis durante a vida universitária. A menos que tenha uma família rica, o mais provável é vir a ter que sofrer um pouco com um orçamento apertado na maioria dos meses. Primeiro, porque o seu dinheiro não vai dar para tudo o que quer fazer, entre saídas à noite, jantares com os amigos e material para as aulas. E depois porque a maioria não está habituada a gerir as suas finanças no dia-a-dia, para que o orçamento chegue até ao fim do mês. Assim, é importante que estabeleça prioridades, defina limites de gastos para cada actividade e que mantenha um registos de despesas e dívidas, para que estas não se acumulem até serem insustentáveis.

2. APRENDA A COLOCAR LIMITES QUANDO SAI À NOITE
A maioria dos estudantes universitários está a viver sozinho e longe dos pais pela primeira vez, o que significa independência e autonomia. Assim como liberdade para sair à noite todos os dias. Por isso, é fácil sair apenas para um copo e acabar numa noitada longa, até de manhã. Não há mal nenhum nisso, mas quando tal acontece quase diariamente acaba por comprometer a sua qualidade de vida e, claro, o aproveitamento escolar. Assim, é fundamental aprender a colocar limites quando sai à noite ou, pelo menos, a estabelecer determinados dias para sair.

3. PLANEIE AS SUAS REFEIÇÕES
Outro hábito a que a maioria dos jovens universitários não estão habituados é a tomar conta da sua alimentação. E isso é um desafio a vários níveis. A tentação inicial é a de ir comer fora sempre ou encomendar de um qualquer serviço de entrega ao domicílio, mas não há orçamento que chega para suportar isso. Também há a tentação de recorrer a comida pré-congelada e outra fast food, o que leva a problemas nutricionais e ate físicos. E, finalmente, há ainda o perigo de deixar para a última esse planeamento e depois faltar tempo para preparas as refeições ou comprar o que falta, levando a uma alimentação deficiente. Assim, é importante planear as suas refeições para a semana, fazer compras atempadamente e, claro, aprender a cozinhar minimamente.

4. NÃO TENHA VERGONHA DE PEDIR AJUDA
A vida universitária tem muitas vezes ritmos e um nível de exigência diferentes ao que estamos habituados. E nem sempre é fácil conciliar o aproveitamento escolar com as lides da casa e outras responsabilidades da vida independente. Por isso, pedir ajuda é natural e não há que ter vergonha de o fazer. Não consegue acompanhar determinada matéria nas aulas? Peça ajuda ao professor ou aos colegas. Não consegue terminar uma aterra doméstica esta semana? Peça ajuda ao colega de casa. Não sabe como controlar os gastos a mais que está a ter? Peça ajuda à família, que têm mais experiência nesse assunto.

5. MANTENHA UMA BOA RELAÇÃO COM OS COLEGAS DE CASA
A vida universitária é também sinónimo de viver com outras pessoas. Não é barato arranjar casa quando se vai estudar para longe e, por isso, a solução mais comum passa por dividir um apartamento com outros estudantes ou um quarto numa residência estudantil. E isso é um desafio muito complicado, uma vez que todas as pessoas são diferentes, com hábitos distintos. Viver com outra pessoa exige cedências de parte a parte. E não é necessário que colegas de casa sejam os melhores amigos, mas uma relação amigável é fundamental para manter uma atmosfera saudável. É que um ambiente difícil em casa leva quase sempre a problemas de aproveitamento escolar. Assim, comunique com o seu colega de casa de forma regular, familiarize-se com as suas rotinas, estabeleçam limites para o bem-estar e conforto um do outro e estabeleçam uma divisão de tarefas domésticas dos espaços comuns.','/images/blog/VxMioAYAZM.jpeg','TENANT');
INSERT INTO blogs(id,slug,title,description,image,category) VALUES ('2b690d27-fa4c-43eb-9915-8b4c82a53f28','wqHAeGwHyc','SAÚDE MENTAL - PENSAR EM TI E NO TEU EQUILÍBRIO EMOCIONAL DURANTE A UNIVERSIDADE','SAÚDE MENTAL - PENSAR EM TI E NO TEU EQUILÍBRIO EMOCIONAL DURANTE A UNIVERSIDADE
A recente emergência higiénico-sanitária, provocada pelo novo coronavirus, veio virar as nossas vidas de pernas para o ar. E entre muitas alterações, veio abrir de vez a porta da praça pública à discussão de um tema muito importante, mas que continuava ainda a ser um tabu na sociedade ocidental: a saúde mental. Apesar de ser algo extremamente importante, parecia haver uma espécie de vergonha e de estigma social sobre este tópico, levando muita gente a sofrer em silêncio e outros tantos a refugiarem-se no trauma.

De facto, a saúde mental não é um tema novo, nem tão pouco uma condição da sociedade moderna, como muitas vezes também se tem a tentação de se resumir. E se a recente pandemia veio criar um cocktail explosivo que deixou a população mais propensa a distúrbios psicológicos, outros sectores da sociedade sempre levantaram preocupação junto dos profissionais. É o caso da vida universitária, um ambiente também muito propício a problemas de saúde mental.
Basta ver os números oficiais para ter uma ideia desta dimensão. Dizem os estudos que 7 em cada 10 estudantes universitário sofrem ou já sofreram de algum problema deste género desencadeado pela vida académica. Isso leva-nos a reflectir sobre o que está a acontecer nas universidades, como é que isso pode ser resolvido e, mais importante ainda, como é que pode ser prevenido. Para se solucionar um problema é fundamentar diagnosticar o problema. E tendo noção e consciência do que se passa, torna muito mais fácil e eficaz enfrenta-lo.

AS CAUSAS QUE AFECTAM A SAÚDE MENTAL NA UNIVERSIDADE
Especialistas têm-se debruçado sobre a vida académica para procurar entender o que leva a esse aumento de problemas emocionais e psicológicos junto dos estudantes. E vários factores têm sido apontados como potenciadores desses distúrbios. Um dos principais é a excessiva carga horária, que leva a um sobrecarregamento dos alunos, incapazes de lidarem com a pressão, com os prazos e com o trabalho académico.

Isso é ainda potenciado pela pressão externa e pelo ambiente de competição, que está cada vez mais enraizado nas universidades. O capitalismo tem a tendência de colocar um valor em tudo e a monetização do aluno, na relação entre a universidade e o mundo do trabalho, leva a essa mistura explosiva que pode afectar a saúde mental do estudante. Tudo isso pode ainda ser influenciado de forma decisiva pela vida social do jovem ou até mesmo pelas suas bases familiares, seja pela falta de apoio, seja pelo excesso de pressão.

Claro que cada caso é um caso e não existem fórmulas mágicas para resolver estas situações. O que é necessário fazer é criar um ambiente seguro para os jovens, indo ao encontro das suas reais necessidades e respectivas motivações. Além disso, a terapia e o acompanhamento psicológico parece ser uma disciplina cada vez ais indispensável no interior da vida académica, já que é isso que permite entender o que se está a passar e como enfrentar esses desafios.

COMO MANTER A SAÚDE MENTAL NA UNIVERSIDADE
Como referimos acima, todas as pessoas são diferentes e não existem fórmulas mágicas para resolver todos os problemas de saúde mental com um estalar de dedos. No entanto, existem várias dicas e conselhos que qualquer estudante pode seguir, de forma a preservar a sua saúde mental e a evitar o desgaste emocional.

Assim, um dos factores decisivos que é apontado por todos os especialistas é a base familiar, que é um apoio fundamental durante o percurso académico. O conselho é então para ficar perto dos que mais ama, já que são estes - seja o núcleo familiar, seja a rede de amigos - que garantem um equilíbrio emocional estável e duradouro. Assim, mantenha uma rotina social, nem que seja necessário reorganizar o seu dia-a-dia.

Esse é, precisamente, outro ponto muito importante para o equilíbrio emocional durante o percurso académico. O planeamento do seu quotidiano é fundamentar para manter o controle da sua vida, encontrando tempo para todas as tarefas, sem que os prazos se acumulem e criem aquele efeito de bola de neve. Além diss, não deve parar nunca, porque só mantendo-se activo é que consegue desenvolver uma vida mais saudável. Além disso, estimula a criatividade e a saúde mental. Finalmente, mas não menos importante, não se refugie em so próprio, seja empático, crie laços pessoais e arranje um escape, para soltar a energia negativa de quando em vez. Tudo isto ajudará a mente ruma saúde mental mais estável e equilibrada.','/images/blog/wqHAeGwHyc.jpeg','TENANT');
INSERT INTO blogs(id,slug,title,description,image,category) VALUES ('d278c900-459e-4451-9366-248801b72681','MfBrBcDVCI','NOVA CIDADE E AGORA? TUDO O QUE PRECISA SABER SOBRE A ADAPTAÇÃO','NOVA CIDADE E AGORA? TUDO O QUE PRECISA SABER SOBRE A ADAPTAÇÃO
Ir estudar para universidade inclui na maioria das vezes a mudança para uma nova cidade, o que além de ser excitante, pode ser também avassalador. Afinal de contas, está a iniciar um novo ciclo na sua vida, com uma mudança brutal nas rotinas, na exigência e no nível de responsabilidade. Por isso, o stress e a ansiedade não é só em fazer a mala e ter o cuidado de não se esquecer de nada.

Assim, existem muitos obstáculos e desafios a ter em conta, de forma a que a adaptação a uma nova cidade corra de forma mais suave. O ideal é mitigar todos os riscos de coisas que possam correr mal, de forma a garantir uma mudança sem incidentes de maior, garantindo uma integração plena. Claro que isso é mais fácil na teoria do que na prática. Contudo, com o planeamento correcto, tudo se torna mais fácil. Assim, para o ajudar nesse processo de mudança, criámos um pequeno guia prático com 5 dicas que pode seguir para garantir uma melhor adaptação a uma nova cidade.

ESCOLHA UMA ACOMODAÇÃO CONFORTÁVEL
É certo que a parte financeira é determinante em qualquer mudança. No entanto, é fundamental, no momento de escolher qual o quarto ou a casa a arrendar, escolher uma opção que seja confortável e que lhe dê garantias de uma vida doméstica que proporcione paz de espírito e saúde mental. As residências de estudantes são as opções mais económicas, mas nem sempre é fácil encontrar vaga. Também os hosteis se tornaram nos últimos tempos em opções válidas e económicas. Contudo, neste caso tem que ter em conta que o seu sossego e tranquilidade pode estar comprometido, porque são locais mais movimentados e barulhento. Ou seja, se for uma pessoa que preza o seu descanso e conforto, talvez esta não seja a opção ideia para si. Além disso, a zona da cidade a escolher também é muito importante, porque não vai querer ficar longe da universidade ou dos serviços, por exemplo. E, finalmente, os extras que a casa tem são também fundamentais para garantir o seu conforto: se a cozinha está ou não equipada, se a internet está incluída, etc.

2. NÃO COMPROMETA AS SUAS NECESSIDADES BÁSICAS
Mudar para uma nova cidade não significa necessariamente colocar termo a actividades que gosta e que costuma fazer. Se tem um passatempo ou se gosta de praticar uma actividade desportiva regular não há qualquer razão para que não o continue a fazer. Mesmo que a vida académica seja mais exigente e que a sua nova vida pessoal passe a ter menos tempo disponível, é fundamental encontrar tempo livre para si mesmo, até mesmo para benefício da sua saúde mental. Assim, procure na nova cidade o local ideal onde poderá praticar desporto ou colocar em prática o seu passatempo preferido e irá ver que se sentirá bem melhor após algum tempo.

3. ESTEJA ATENTO À VIDA SOCIAL E CULTURAL LOCAL
Mudar-se para uma nova cidade implica descobrir as rotinas e as dinâmicas locais. Isso é importante para garantir uma inclusão plena e uma fruição da cidade total. Assim, procure manter-se actualizado acerca das actividades que acontecem na sua zona. Descarregue e instale algumas aplicações que o possam ajudar nesse sentido, junte-se a grupos locais no Facebook e leia regularmente a agenda cultural. Certamente irá encontrar actividades que lhe agradarão e que gostará de visitar, onde provavelmente até irá conhecer mais pessoas e novos amigos. Além disso, sentir-se-á como parte integrante da comunidade local e não apenas como um estranho, contribuindo para a sua total inclusão.

4. ESTUDE FORA DE CASA TAMBÉM
Nem sempre é possível estudar ou trabalhar fora do conforto do lar, onde tem a garantia de tranquilidade e sossego. No entanto, nos primeiros tempos a vive numa nova cidade, pode ser importante ir estudar algumas vezes para outros locais. Seja numa esplanada, na biblioteca da escola ou mesmo num escritório de co-working, isso irá permitir-se espairecer, conhecer novos locais e, possivelmente, novas pessoas, assim como estabelecer dinâmicas diferentes e mais inclusivas com a cidade. É ainda uma dica muito importante que contribui para uma melhor saúde mental e que até pode contribuir para um desemprenho académico mais satisfatório.

5. DÊ TEMPO AO TEMPO
Mudar para uma nova cidade pode resultar num período de choque cultural, que dependendo da pessoa pode ser mais ou menos longo. Por isso, é natural que se sinta assoberbado nos primeiros tempos. Não se deixe abater e, mesmo que a ideia de desistir lhe venha à mente, não se deixe vencer por ela. É perfeitamente normal demorar algum tempo a ajustar-se à nova vida, às novas rotinas e às novas pessoas. Por isso, dê tempo ao tempo e não force nada. É fundamental sentir-se bem consigo próprio e confortável. Procure manter contacto regular com a sua familia e amigos, já que uma base estável é muito importante em qualquer mudança significativa na sua vida. E verá que, com o passar do tempo, a sua aventura começará a tornar-se cada vez mais familiar. ','/images/blog/MfBrBcDVCI.jpeg','TENANT');
INSERT INTO blogs(id,slug,title,description,image,category) VALUES ('e9c70a70-c3c9-44bd-8f67-a91b6a092ffe','LBwDYycFXx','PAGAMENTOS: O MEU INQUILINO DEIXOU DE PAGAR. E AGORA?','PAGAMENTOS: O MEU INQUILINO DEIXOU DE PAGAR. E AGORA?
Um dos maiores pesadelos de um proprietário é o do inquilino deixar de pagar a renda. A lei é muito clara sobre o que fazer nestes casos, mas nem sempre a sua aplicação é tão simples quanto isso. Além disso, a lei protege o arrendatário - e bem -, o que faz com que certos casos acabem por se tornar também mais difíceis ou morosos de resolver. 

Segundo a lei em vigor, existem duas situações em que o arrendatário entra em incumprimento e, nas quais, o proprietário pode denunciar o contrato. É quando esse se atrasa no pagamento num prazo superior a oito dias por mais de quatro vezes no período de um ano. E é quando o arrendatário tem em atraso a renda por mais de dois meses.

COMO FAZER A DENÚNCIA DO CONTRATO DE ARRENDAMENTO
Perante um desses dois casos que enunciámos no parágrafo acima, o senhorio está protegido pela lei para proceder à denuncia do contrato de arrendamento da sua propriedade. Para isso, deve comunica-lo aos inquilinos através de carta registada, com aviso de recepção, de forma a ter a certeza de que esta é recebida. Nessa carta deve comunicar a sua intenção e, de forma clara, indicar o incumprimento em causa, o montante em falta e as datas respectivas.

Caso prefira, pode também transmitir essa informação através de um representante legal, que pode ser um advogado, um solicitador ou um agente de execução. No entanto, é óbvio que essa opção tem custos associados. Depois de receber a carta, o arrendatário tem ainda um mês para regularizar a situação. Se o fizer, a situação deixa de estar em incumprimento legal. Mas atenção que este é um procedimento que apenas pode acontecer uma única vez durante todo o período estabelecido no contrato de arrendamento celebrado entre as partes.

Depois disto, se o inquino continuar a não pagar a renda, o proprietário pode recorrer novamente à lei para fazer valer os seus direitos. Nesse caso, pode solicitar um procedimento especial de despejo por rendas vencidas. Depois de notificado, o arrendatário tem um prazo de 10 dias para abandonar o imóvel. Contudo, é de realçar que apenas os proprietários que tenham as suas contribuições fiscais regularizadas é que podem recorrer a esta ferramenta jurídica legal. 

Finalmente, mas não menos importante, para finalizar o pedido de despejo o proprietário deve ainda efectuar o pedido junto do Banco Nacional de Arrendamento, para o qual existe um formulário específico. Este deve ser entregue juntamente com uma cópia do contrato de arrendamento, o comprovativo de pagamento do imposto de ser e uma cópia da carta enviada ao arrendatário. Além disso, há uma taxa a pagar de 25 euros e 50 cêntimos.

COMO RESCINDIR O CONTRATO DE ARRENDAMENTO
A rescisão do contrato de arrendamento também é uma situação que pode ocorrer entre senhorio e inquilino e está prevista na lei portuguesa, se bem que salvaguardando ambas as partes. Contudo, existem vários factores a ter em consideração, especialmente desde a lei que foi aprovada em 2019 no Parlamento português, que pretendeu corrigir vários desequilíbrios que existiam.

Assim, os contratos de arrendamento têm que ter sempre um mínimo de 12 meses. Além disso, são ainda automaticamente renováveis por três anos, a não ser que esteja previsto no contrato outra situação. Obviamente que isso não se adequa aos contratos de arrendamento turístico, que não têm duração mínima e não estão sujeitos a qualquer tipo de renovação automática.

O inquilino pode ainda avançar para a rescisão do contrato de arrendamento perante outras situações excepcionais, além do incumprimento de pagamento por parte do inquilino. É o caso de, por exemplo, o imóvel vir a ser demolido. Quanto a casos de obras, o contrato fica apenas suspenso, se bem que o inquilino tem direito a ser realizado numa casa equivalente. Caso nenhuma dessas opções seja possível, o proprietário é obrigado a reembolsar o inquino monetariamente.

Finalmente, mas não menos importante, destaque ainda para casos de renovação do contrato. Caso este se esteja a aproximar do final e o proprietário não deseja proceder à sua extensão, deve comunicar ao inquilino dentro do prazo previsto por lei. Para contratos de 1 ano, essa comunicação deve ser feita até 60 dias antes do seu término. Para contratos até 6 anos de duração, o prazo é de 90 dias. E para todos os contratos superiores a 6 anos, esse prazo sobre até aos 120 dias.','/images/blog/LBwDYycFXx.jpeg','LANDLORD');
INSERT INTO blogs(id,slug,title,description,image,category) VALUES ('4859d71b-ff6f-407e-88b0-40c1c094ca1c','GjLjumMoXe','5 FORMAS DE MELHORAR O CONSUMO ENERGÉTICO DA SUA CASA','5 FORMAS DE MELHORAR O CONSUMO ENERGÉTICO DA SUA CASA
É certo que Portugal tem melhorado muito no que diz respeito ao consumo energético das suas casas, devido à implementação de várias políticas que visam a eficiência nesse campo. No entanto, ainda muito há para fazer. Segundo os últimos relatórios oficiais, Portugal passou da posição 27 para o 7º lugar no ranking do Wnergy Efficiency Watch Survey. Contudo, a maioria dos portugueses continua sem conseguir aquecer as suas casas, devido à conjugação explosiva de dois factores predominantes: o alto preço da energia e a construção deficiente dos imóveis.

A factura da electricidade ao fim do mês é mesmo um dos principias encargos de qualquer família no final do mês. E pior do que uma factura de electricidade só mesmo duas facturas de electricidade, que é o que acontece aos proprietários, que têm uma casa arrendada com as contas incluídas ou no mercado turístico. Como é impossível pedir aos proprietários para consumir menos energia, a solução passa então por reduzir esses encargos. Mas como?

A solução não é fácil e é apenas relativa. No entanto, existem alguns conselhos que pode implementar na sua propriedade, de forma a aumentar a eficiência e a reduzir o desperdício energético. Assim, vá buscar o seu Certificado de Eficiência Energética, que representa o desempenho energético do seu imóvel, e siga estas 5 dicas de forma a alterar a sua classificação até à letra A, que significa que atingiu o topo no que diz respeito à poupança energética.

OPTE POR UMA FONTE DE ENERGIA MAIS VERDE
Vivemos em plena crise ambiental e já não é possível ignorar que é preciso mudarmos os nossos hábitos de consumo. Se não adoptarmos comportamentos mais verdes e sustentáveis, o futuro como o conhecemos será obrigatoriamente diferente. E essa mudança começa connosco mesmos, nos nossos pequenos gestos e an própria casa. Assim, a alteração da fonte energética do seu imóvel para uma solução mais amiga do ambiente não só é mais sustentável, como é também mais eficiente e, consequentemente, mais económica. Compare assim preços de opções como o gás natural, por exemplo, e procure fazer simulações a médio e longo prazo, porque às vezes a poupança não se reflecte no imediato.

2. TENHA EM CONSIDERAÇÃO A EXPOSIÇÃO SOLAR
Se está a pensar em investir numa propriedade, então é altura de começar a ter também em conta a eficiência energética, já que isso poderá vir a ser fundamental do ponto de vista financeiro. E uma das formas é ter em consideração a sua exposição solar. É que uma casa com luz natural elevada e predominante não só reduz os custos da electricidade, com não exige tanto de equipamentos de aquecimento. Não é por acaso que essa é uma característica que influencia determinantemente o preço dos imóveis. Por isso, se for adquirir casa, opte sempre por opções com boa exposição solar e orientadas a sul.

3. INSTALE LÂMPADAS DE BAIXO CONUSMO
As lâmpadas incandescentes estão a desaparecer, mas a sua transição para as lâmpadas de LED ainda não está tolamente concluída. Se for o seu caso, faça essa alteração. Afinal de contas, as lâmpadas LED podem resultar numa poupança até 90 por cento do seu consumo actual. É que além de gastarem menos, estas lâmpadas têm uma durabilidade maior, podendo ir até 10 anos de vida. O mesmo acontece com os electrodomésticos. Sempre que precisar de substituir um dos aparelhos de casa, opte por modelos mais económicos e mais eficientes energeticamente. Eles até podem representar um investimento maior, mas a médio e longo prazo vão justificaresse gasto maior sem qualquer margem para dúvidas. 

4. REFORCE O ISOLAMENTO TÉRMICO
Como já referimos acima, um dos grandes problemas das casas em Portugal prende-se com a sua deficiente construção, que se reflecte num deficiente isolamento térmico. Tudo isso cria um ciclo vicioso, já que vai exigir um maior recurso a equipamento de aquecimento e, claro, um consequente aumento da factura da electricidade ao fim do mês. O isolamento térmico das paredes e do pavimento é assim uma intervenção que pode fazer na sua propriedade de forma a aumentar a sua eficiência energética, garantindo mais aquecimento no inverno e menor sobre-aquecimento no inverno. Também a instalação de janelas de vidros duplos ajudam a potenciar esse isolamento térmico.
´
5. POUPE ÁGUA
A água é um dos recursos mais importantes do mundo e, apesar de o tomarmos por garantido, a sua escassez começa a ser já um problema à escala mundial. Além disso, adoptar estratégias e técnicas para o consumo de água ajudam também a aumentar a eficiência energética da sua propriedade. Assim, opte por instalar torneiras como regulação de fluxo ou autoclismos com sistema de dupla descarga. Além disso, pode também optar por bombas de calor em vez dos tradicionais termoacumuladores ou esquentadores, até porque são também soluções mais ecológicas.','/images/blog/GjLjumMoXe.jpeg','LANDLORD');
INSERT INTO blogs(id,slug,title,description,image,category) VALUES ('50d9be44-2ef1-4cfb-9d23-6588ec4b9850','fxMclORyAR','5 DICAS IMPORTANTES PARA OS SENHORIOS','5 DICAS IMPORTANTES PARA OS SENHORIOS
O mercado imobiliário e o de arrendamento são dois sectores que andam de mão dada e que são óptimos investimentos, especialmente a médio e longo prazo. Afinal de contas, os imóveis nunca desvalorizam, antes pelo contrário, e o mercado de arrendamento está menos sujeito a quebras de procura e a factores externos, como acontece por vezes com o do alojamento turístico. A crise financeira de 2008 e a actual emergência higiénico-sanitária, provocada pelo novo coronavirus, são dois bons e recentes exemplos de como o alojamento turístico é um mercado facilmente volátil.

No entanto, ser senhorio não é fácil. As promessas de rendimento fácil podem ser verdade, mas exigem dedicação e trabalho. Mesmo não sendo uma ocupação profissional a tempo inteiro, é algo que necessita de acompanhamento regular. E, tal como tudo na vida, a planificação prévia ajuda a prevenir incidentes, a reduzir custos e a optimizar o tempo e o trabalho. Assim, para o ajudar nessa tarefa, compilámos 5 dicas importantes para todos os senhorios que estão a começar no mercado de arrendamento.

A SUA PROPRIEDADE É TAMBÉM UM NEGÓCIO
Muitas vezes, os senhorios têm a tentação de olhar para um arrendamento como uma ocupação secundária para ganhar algo dinheiro extra. Isso não é errado ou falso, mas arrendar uma casa é mais sério que isso. E, portanto, é fundamental que o encare como um negócio, colocando seriedade e profissionalismo na forma como aborda a questão. Primeiro que tudo é fundamental manter uma relação altamente profissional com os arrendatários, estabelecido igualmente uma relação de confiança. E depois, tal como em qualquer negócio, é fundamental respeitar todas as normas de segurança ou exigências legais, proteger-se contra acidentes com os seguros certos e manter o imóvel com boas condições de salubridade, até porque isso previne o aparecimento de complicações mais caras.

2. CONSIDERE CONTRATAR UMA EMPRESA DE GESTÃO DE IMÓVEIS
Ser senhorio pode consumir muito do seu tempo, especialmente se tiver mais do que um imóvel. Por isso, considerar a possibilidade de contratar uma empresa de gestão de propriedades ou de condomínios é uma ideia forte, que pode ser proveitosa. É certo que isso exige um investimento considerável, mas na maioria das vezes isso compensa pelo tempo que ganha e as preocupações que evita. Além disso, ao delegar essa tarefa num profissional deixa de ter que estar sempre disponível para atender a qualquer emergência na propriedade. 

3. ESTABELEÇA UM VALOR DE RENDA JUSTO
O mercado imobiliário em geral e o de arrendamento em particular é extremamente volátil e muito dado à inflação. Por isso, é também muito tentador, levando a que muitos proprietários se estiquem nas rendas, em busca de dinheiro rápido e fácil. No entanto, isso pode comprometer o seu imóvel a médio e longo prazo. Rendas muito altas podem causar sobrecarga em determinadas zonas urbanas, levando à redução da procura e à desvalorização do imóvel, comprometendo o seu futuro financeiro. Assim, considere todas as despesas anuais que tem com o imóvel e estabeleça uma renda que seja justa para si, mas também para o possível arrendatário.

4. MANTENHA UM CONTACTO REGULAR COM O ARRENDATÁRIO
A comunicação é sempre uma ferramenta fundamental para qualquer relação, seja ela familiar ou pessoal. E neste caso não é excepção. Um contacto regular, mas profissional, com o arrendatário ajuda a manter uma relação de proximidade, a criar um ambiente de confiança e a prevenir possível conflitos futuros. Não existe qualquer razão para hostilizar o arrendatário, antes pelo contrário. Ele é um aliado seu e, tal como o proprietário, só tem a ganhar com essa relação próxima. 

5. FAÇA SEMPRE CONTRATO
Fazer contrato e regista-lo nas Finanças pode encarecer as suas despesas anuais e, por isso, pode ser tentador procura uma via alternativa de efectuar o arrendamento do seu imóvel. No entanto, além de isso ser ilegal, é também uma forma de levar a outros possíveis problemas. É que o contrato é uma ferramenta legal que o protege em caso de conflito, já que lhe permite recorrer a instituições reguladores para solucionar problemas que possam surgir com o arrendatário e não só. Além disso, pode também levar a despesas extras, como por exemplo muitas associadas. Finalmente, mas não menos importante, com contrato está também a ajudar fiscalmente o arrendatário, ao mesmo tempo que lhe dá a legitimidade para fazer certas exigências, como o pagamento de caução, por exemplo. ','/images/blog/fxMclORyAR.jpeg','LANDLORD');
INSERT INTO blogs(id,slug,title,description,image,category) VALUES ('4913a61f-f5f2-4e89-9b08-43c744a2084e','MwlasmlrEg','ANIMAIS DE ESTIMAÇÃO: SIM OU NÃO? E QUE CUIDADOS DEVE TER?','ANIMAIS DE ESTIMAÇÃO: SIM OU NÃO? E QUE CUIDADOS DEVE TER?
Aceitar ou não aceitar animais de estimação nos imóveis, eis uma das grandes questões que apoquentam desde sempre os proprietários. É natural que haja uma grande tentação dos senhorios em proibirem cães ou gatos nos seus imóveis, de forma a salvaguardarem a integridade da propriedade, mas não vai contra a liberdade dos arrendatários? E a questão do ruído para os vizinhos, não é também uma questão a ter em conta?
De forma a colocar um ponto final nesta discussão, o Governo português regulamentou a questão em 2019, com a contribuição dos partidos com assento parlamentar. Assim, a lei nacional não proíbe a existência de animais nos apartamentos, o que significa que é ilegal que o proprietário coloque algum tipo de restrições neste sentido. Contudo, existem limites. Por apartamento não podem existir mais do que quatro animais, sendo que cães só podem ir até três.

Naturalmente, qualquer possível dano provocado pelo animal será da responsabilidade do arrendatário, da mesma forma que isso acontece se esse for provocado pelo próprio, por um familiar ou um amigo seu. Também as questões relacionadas com a higiene do animal são da total responsabilidade do arrendatário, como é óbvio. E este é igualmente responsável por garantir o direito ao descanso dos vizinhos, ou seja, salvaguardando todas as questões relacionadas ao ruído excessivo, especialmente durante o período da noite.

CUIDADOS A TER PARA PREVENIR INCIDENTES COM ANIMAIS DE ESTIMAÇÃO
Sendo assim, perante a pergunta “animais de estimação, sim ou não?”, a resposta é clara e apenas uma: sim, claro. Sempre, aliás. Até porque não há razão para se proibir tal facto. No entanto, também é verdade que existe alguns cuidados que os proprietários podem ter para salvaguardar incidentes maiores. Afinal de contas, já diz o adágio que mais vale prevenir do que remediar. E a sabedoria popular não se costuma enganar muitas vezes.

Assim, apesar da lei ser clara e do cidadão não poder alegar o seu desconhecimento, o proprietário não tem nada a perder em deixar todos esses deveres bem explanados no contrato. Para isso, pode perguntar ao arrendatário se tem animais de estimação. Se a resposta for afirmativa, então essas tarefas podem e devem vir explanadas no contrato de arrendamento: que deve haver silêncio a partir das 22 horas, que a higiene do animal é da responsabilidade do seu dono e, claro, quaisquer danos serão imputados a si.

Além disso, pode sempre ajudar o arrendatário com informações que lhe poderão ser úteis. Muitas vezes, os arrendatários são novos na cidade e não estão familiarizados com a zona. Assim, pode ser muito importante saberem onde é o veterinário mais próximo ou o parque onde poderão passear o seu cão, por exemplo. No fundo, o diálogo é uma ferramenta fundamental para prevenir qualquer incidente, especialmente em situações como esta.

BENEFÍCIOS PARA A SAÚDE DOS ANIMAIS DE ESTIMAÇÃO
Toda a gente sabe que um animal de estimação faz companhia e donos amor incondicional, mas os seus benefícios vão muito mais além disso do que pensamos. Na verdade, vários estudos têm procurado produzir evidência nos últimos anos sobre as vantagens dos animais para a nossa saúde física e mental, incluindo na prevenção de doenças.

De facto, longe vão os tempos em que se acreditava que os animais, nomeadamente os gatos, eram fontes de alergias, especialmente para as crianças. Contudo, alguns estudos apontaram que os cães podem ajudar a reduzir o risco dos jovens desenvolverem alergias ou até mesmo problemas respiratórios, como a asma. Além disso, também têm havido estudos que mostram alguma relação entre ter um animal de estimação e a redução do risco de desenvolvimento de doença cardíaca. Obviamente que é necessário efectuar mais estudos neste sentido, mas é um excelente indício.

Finalmente, a interacção com um animal de estimação é ainda um óptimo remédio na gestão do stress e da ansiedade diária. A explicação é simples e a ciência explica-o. O organismo produz dopamimna e serotonina, responsáveis pela sensação de prazer e com poderosas propriedades calmantes. E isso, numa altura em que o estilo de vida ocidental é pródigo em doenças do foro psicológico, acaba por ser duplamente positivo. Portanto, não é de admirar que cada vez mais pessoas optem por adoptarem um animal de estimação, especialmente um cão ou um gato.','/images/blog/MwlasmlrEg.jpeg','LANDLORD');
