import { Database } from "../database.types";
import {
  GENERAL_ADMIN_URL,
  HOME_URL,
  INBOX_URL,
  UNIDESK_SENHORIO_PAINEL_URL,
  UNIDESK_SENHORIO_REVIEWS_URL,
  UNIDESK_STAY_URL,
} from "./paths";

export const FAVORITE_TABLE_NAME = "favorites" as const;

export type FavoriteResponse = Database["public"]["Tables"]["favorites"];
export type Favorite = FavoriteResponse["Row"];

/* VALUES FOR DB */
export const FAVORITE_PROPERTIES = {
  PROFILE_ID: "profile_id",
  ID: "id",
  ADVERTISEMENT_ID: "advertisement_id"
} as const;

export const FAVORITE_LINKS = {
  STUDENT_EVALUATE_STAY: UNIDESK_STAY_URL,
  STUDENT_RESERVATION_DECLINED: UNIDESK_STAY_URL,
  STUDENT_RESERVATION_ACCEPTED: UNIDESK_STAY_URL,
  STUDENT_UNIHOSTS_SUPPORT: HOME_URL,
  STUDENT_COMPLETE_PROFILE: GENERAL_ADMIN_URL,
  LANDLORD_RESERVATION_RECEIVED: INBOX_URL,
  LANDLORD_UNIHOSTS_SUPPORT: HOME_URL,
  LANDLORD_NEW_REVIEW: UNIDESK_SENHORIO_REVIEWS_URL,
  LANDLORD_COMPLETE_PROFILE: GENERAL_ADMIN_URL,
  LANDLORD_COMPLETE_ADVERT: UNIDESK_SENHORIO_PAINEL_URL,
  BLOG: HOME_URL,
};

